// This file is automatically generated. Do not modify it manually.
// You can get a new configuration object from the "Connect" page in the
// Firebase console.

export const firebaseConfig = {
  apiKey: "AIzaSyD0YHKSP5hdVVl_n34TOqZ2yr8Nsg-qX9c",
  authDomain: "menuqr-ea239.firebaseapp.com",
  projectId: "menuqr-ea239",
  storageBucket: "menuqr-ea239.appspot.com",
  messagingSenderId: "430028705581",
  appId: "1:430028705581:web:fd448c892081c45e150da4",
  measurementId: "G-1880L738R3"
};
